-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.achievements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code character varying NOT NULL UNIQUE,
  name character varying NOT NULL,
  description text NOT NULL,
  category character varying NOT NULL,
  requirements jsonb NOT NULL,
  reward_exp integer DEFAULT 0,
  reward_items jsonb DEFAULT '[]'::jsonb,
  rarity character varying DEFAULT 'common'::character varying,
  icon character varying,
  is_active boolean DEFAULT true,
  is_hidden boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT achievements_pkey PRIMARY KEY (id)
);
CREATE TABLE public.ai_analysis_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  restaurant_id uuid NOT NULL,
  analysis_type character varying NOT NULL,
  analysis_scope character varying,
  input_data jsonb NOT NULL,
  parameters jsonb,
  ai_response text NOT NULL,
  result_data jsonb,
  confidence_score numeric,
  execution_time_ms integer,
  model_version character varying,
  created_by character varying,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ai_analysis_logs_pkey PRIMARY KEY (id),
  CONSTRAINT ai_analysis_logs_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id)
);
CREATE TABLE public.ai_evolution_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  ai_pet_id uuid NOT NULL,
  evolution_type character varying NOT NULL,
  trigger_event character varying,
  changes_made jsonb NOT NULL,
  previous_state jsonb,
  new_state jsonb,
  interaction_count integer,
  user_satisfaction numeric,
  learning_data jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ai_evolution_log_pkey PRIMARY KEY (id),
  CONSTRAINT ai_evolution_log_ai_pet_id_fkey FOREIGN KEY (ai_pet_id) REFERENCES public.ai_pets(id)
);
CREATE TABLE public.ai_interactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  ai_pet_id uuid NOT NULL,
  session_id uuid,
  user_message text NOT NULL,
  ai_response text NOT NULL,
  interaction_type character varying DEFAULT 'chat'::character varying,
  user_sentiment character varying,
  user_emotion jsonb,
  ai_emotional_response character varying,
  intent_detected character varying,
  service_provided character varying,
  recommendation_made jsonb DEFAULT '[]'::jsonb,
  recommendation_accepted boolean,
  satisfaction_rating integer CHECK (satisfaction_rating >= 1 AND satisfaction_rating <= 5),
  feedback_text text,
  learning_points integer DEFAULT 1,
  personality_adjustments jsonb DEFAULT '{}'::jsonb,
  preference_updates jsonb DEFAULT '{}'::jsonb,
  response_time_ms integer,
  interaction_duration_ms integer,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ai_interactions_pkey PRIMARY KEY (id),
  CONSTRAINT ai_interactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT ai_interactions_ai_pet_id_fkey FOREIGN KEY (ai_pet_id) REFERENCES public.ai_pets(id)
);
CREATE TABLE public.ai_performance_metrics (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  restaurant_id uuid NOT NULL,
  metric_date date NOT NULL,
  metric_hour integer CHECK (metric_hour >= 0 AND metric_hour <= 23),
  table_utilization_rate numeric,
  average_wait_time_minutes integer,
  kitchen_efficiency_score numeric,
  service_speed_score numeric,
  demand_forecast_accuracy numeric,
  prep_time_prediction_accuracy numeric,
  ai_driven_revenue numeric,
  cost_savings numeric,
  waste_reduction_percentage numeric,
  customer_satisfaction_score numeric,
  order_accuracy_rate numeric,
  complaint_resolution_time integer,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ai_performance_metrics_pkey PRIMARY KEY (id),
  CONSTRAINT ai_performance_metrics_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id)
);
CREATE TABLE public.ai_pets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  name character varying DEFAULT 'AI助手'::character varying,
  avatar character varying DEFAULT 'default_ai'::character varying,
  birth_date timestamp with time zone DEFAULT now(),
  level integer DEFAULT 1 CHECK (level >= 1 AND level <= 10),
  experience_points integer DEFAULT 0,
  next_level_exp integer DEFAULT 100,
  friendliness integer DEFAULT 50 CHECK (friendliness >= 0 AND friendliness <= 100),
  formality integer DEFAULT 70 CHECK (formality >= 0 AND formality <= 100),
  proactivity integer DEFAULT 30 CHECK (proactivity >= 0 AND proactivity <= 100),
  humor integer DEFAULT 40 CHECK (humor >= 0 AND humor <= 100),
  memory_focus character varying DEFAULT 'taste'::character varying,
  learning_speed numeric DEFAULT 1.0,
  adaptation_rate numeric DEFAULT 1.0,
  total_conversations integer DEFAULT 0,
  successful_recommendations integer DEFAULT 0,
  customer_satisfaction_avg numeric DEFAULT 5.0,
  mood character varying DEFAULT 'neutral'::character varying,
  energy_level integer DEFAULT 100 CHECK (energy_level >= 0 AND energy_level <= 100),
  special_abilities jsonb DEFAULT '[]'::jsonb,
  personality_quirks jsonb DEFAULT '[]'::jsonb,
  evolution_history jsonb DEFAULT '[]'::jsonb,
  milestones_achieved jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  last_interaction_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ai_pets_pkey PRIMARY KEY (id),
  CONSTRAINT ai_pets_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.ai_recommendations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  restaurant_id uuid NOT NULL,
  recommendation_type character varying NOT NULL,
  category character varying,
  priority integer DEFAULT 3 CHECK (priority >= 1 AND priority <= 5),
  title character varying NOT NULL,
  description text NOT NULL,
  action_items jsonb,
  estimated_impact jsonb,
  confidence_score numeric,
  target_entity character varying,
  target_id uuid,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'reviewed'::character varying, 'accepted'::character varying, 'rejected'::character varying, 'implemented'::character varying]::text[])),
  expires_at timestamp with time zone,
  feedback jsonb,
  implementation_notes text,
  reviewed_by character varying,
  implemented_by character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ai_recommendations_pkey PRIMARY KEY (id),
  CONSTRAINT ai_recommendations_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id)
);
CREATE TABLE public.analytics_events (
  id bigint NOT NULL DEFAULT nextval('analytics_events_id_seq'::regclass),
  user_id uuid,
  event_name text NOT NULL,
  event_time timestamp with time zone DEFAULT now(),
  metadata jsonb,
  CONSTRAINT analytics_events_pkey PRIMARY KEY (id),
  CONSTRAINT analytics_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  restaurant_id uuid NOT NULL,
  table_name character varying NOT NULL,
  record_id uuid,
  action character varying NOT NULL,
  old_data jsonb,
  new_data jsonb,
  changed_fields jsonb,
  user_id character varying,
  user_type character varying,
  ip_address inet,
  user_agent text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id)
);
CREATE TABLE public.categories (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  restaurant_id uuid NOT NULL,
  name character varying NOT NULL,
  description text,
  sort_order integer DEFAULT 0,
  color character varying DEFAULT '#3B82F6'::character varying,
  icon character varying DEFAULT '🍽️'::character varying,
  image_url text,
  parent_id uuid,
  level integer DEFAULT 1,
  path text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  ai_visibility_score numeric DEFAULT 1.0,
  ai_popularity_rank integer,
  metadata jsonb,
  CONSTRAINT categories_pkey PRIMARY KEY (id),
  CONSTRAINT categories_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.categories(id),
  CONSTRAINT categories_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id)
);
CREATE TABLE public.combo_products (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  restaurant_id uuid NOT NULL,
  category_id uuid,
  name character varying NOT NULL,
  description text,
  price numeric NOT NULL,
  cost numeric DEFAULT 0,
  combo_type character varying NOT NULL CHECK (combo_type::text = ANY (ARRAY['fixed'::character varying, 'selectable'::character varying, 'build_your_own'::character varying]::text[])),
  image_url text,
  sort_order integer DEFAULT 0,
  is_available boolean DEFAULT true,
  is_active boolean DEFAULT true,
  preparation_time integer DEFAULT 15,
  availability_start time without time zone,
  availability_end time without time zone,
  available_days jsonb,
  min_items integer DEFAULT 1,
  max_items integer,
  discount_type character varying DEFAULT 'fixed'::character varying,
  discount_value numeric DEFAULT 0,
  ai_popularity_score numeric DEFAULT 0.5,
  ai_recommended boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  metadata jsonb,
  CONSTRAINT combo_products_pkey PRIMARY KEY (id),
  CONSTRAINT combo_products_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(id),
  CONSTRAINT combo_products_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id)
);
CREATE TABLE public.combo_selection_options (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  rule_id uuid NOT NULL,
  product_id uuid NOT NULL,
  additional_price numeric DEFAULT 0,
  is_default boolean DEFAULT false,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT combo_selection_options_pkey PRIMARY KEY (id),
  CONSTRAINT combo_selection_options_rule_id_fkey FOREIGN KEY (rule_id) REFERENCES public.combo_selection_rules(id),
  CONSTRAINT combo_selection_options_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.combo_selection_rules (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  combo_id uuid NOT NULL,
  category_id uuid,
  selection_name character varying NOT NULL,
  description text,
  min_selections integer DEFAULT 1,
  max_selections integer DEFAULT 1,
  is_required boolean DEFAULT true,
  display_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT combo_selection_rules_pkey PRIMARY KEY (id),
  CONSTRAINT combo_selection_rules_combo_id_fkey FOREIGN KEY (combo_id) REFERENCES public.combo_products(id),
  CONSTRAINT combo_selection_rules_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(id)
);
CREATE TABLE public.customer_coupons (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  customer_id uuid NOT NULL,
  coupon_code character varying NOT NULL UNIQUE,
  title character varying NOT NULL,
  description text,
  discount_type character varying NOT NULL,
  discount_value numeric,
  minimum_order_amount numeric DEFAULT 0,
  maximum_discount_amount numeric,
  applicable_items jsonb,
  usage_limit integer DEFAULT 1,
  used_count integer DEFAULT 0,
  valid_from timestamp with time zone DEFAULT now(),
  valid_until timestamp with time zone NOT NULL,
  is_active boolean DEFAULT true,
  source character varying,
  created_at timestamp with time zone DEFAULT now(),
  used_at timestamp with time zone,
  CONSTRAINT customer_coupons_pkey PRIMARY KEY (id),
  CONSTRAINT customer_coupons_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customer_users(id)
);
CREATE TABLE public.customer_favorites (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  customer_id uuid NOT NULL,
  product_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT customer_favorites_pkey PRIMARY KEY (id),
  CONSTRAINT customer_favorites_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customer_users(id),
  CONSTRAINT customer_favorites_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.customer_orders (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  customer_id uuid NOT NULL,
  order_number character varying NOT NULL UNIQUE,
  table_id uuid,
  order_type character varying DEFAULT 'dine_in'::character varying,
  status character varying DEFAULT 'pending'::character varying,
  items jsonb NOT NULL,
  subtotal numeric NOT NULL,
  tax_amount numeric DEFAULT 0,
  discount_amount numeric DEFAULT 0,
  points_used integer DEFAULT 0,
  points_earned integer DEFAULT 0,
  total_amount numeric NOT NULL,
  payment_method character varying,
  payment_status character varying DEFAULT 'pending'::character varying,
  notes text,
  delivery_address jsonb,
  estimated_ready_time timestamp with time zone,
  completed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT customer_orders_pkey PRIMARY KEY (id),
  CONSTRAINT customer_orders_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customer_users(id),
  CONSTRAINT customer_orders_table_id_fkey FOREIGN KEY (table_id) REFERENCES public.tables(id)
);
CREATE TABLE public.customer_points (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  customer_id uuid NOT NULL,
  points_balance integer DEFAULT 0,
  total_earned integer DEFAULT 0,
  total_redeemed integer DEFAULT 0,
  tier character varying DEFAULT 'bronze'::character varying,
  tier_expires_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT customer_points_pkey PRIMARY KEY (id),
  CONSTRAINT customer_points_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customer_users(id)
);
CREATE TABLE public.customer_points_transactions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  customer_id uuid NOT NULL,
  type character varying NOT NULL,
  points integer NOT NULL,
  balance_after integer NOT NULL,
  reference_type character varying,
  reference_id uuid,
  description text,
  expires_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  CONSTRAINT customer_points_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT customer_points_transactions_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customer_users(id)
);
CREATE TABLE public.customer_preferences (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  spice_tolerance integer DEFAULT 3 CHECK (spice_tolerance >= 1 AND spice_tolerance <= 5),
  sweet_preference integer DEFAULT 3 CHECK (sweet_preference >= 1 AND sweet_preference <= 5),
  sour_preference integer DEFAULT 3 CHECK (sour_preference >= 1 AND sour_preference <= 5),
  salty_preference integer DEFAULT 3 CHECK (salty_preference >= 1 AND salty_preference <= 5),
  dietary_restrictions jsonb DEFAULT '[]'::jsonb,
  allergens jsonb DEFAULT '[]'::jsonb,
  avoided_ingredients jsonb DEFAULT '[]'::jsonb,
  preferred_cuisines jsonb DEFAULT '[]'::jsonb,
  favorite_dishes jsonb DEFAULT '[]'::jsonb,
  disliked_dishes jsonb DEFAULT '[]'::jsonb,
  ordering_frequency character varying DEFAULT 'monthly'::character varying,
  avg_order_value numeric DEFAULT 0,
  preferred_meal_times jsonb DEFAULT '[]'::jsonb,
  party_size_usual integer DEFAULT 2,
  decision_speed character varying DEFAULT 'moderate'::character varying,
  price_sensitivity character varying DEFAULT 'moderate'::character varying,
  adventurous_level integer DEFAULT 5 CHECK (adventurous_level >= 1 AND adventurous_level <= 10),
  confidence_scores jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT customer_preferences_pkey PRIMARY KEY (id),
  CONSTRAINT customer_preferences_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.customer_reservations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  customer_id uuid NOT NULL,
  table_id uuid,
  reservation_date date NOT NULL,
  reservation_time time without time zone NOT NULL,
  party_size integer NOT NULL,
  status character varying DEFAULT 'pending'::character varying,
  special_requests text,
  contact_phone character varying,
  contact_email character varying,
  reminder_sent boolean DEFAULT false,
  check_in_time timestamp with time zone,
  seated_time timestamp with time zone,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  cancelled_at timestamp with time zone,
  cancellation_reason text,
  CONSTRAINT customer_reservations_pkey PRIMARY KEY (id),
  CONSTRAINT customer_reservations_table_id_fkey FOREIGN KEY (table_id) REFERENCES public.tables(id),
  CONSTRAINT customer_reservations_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customer_users(id)
);
CREATE TABLE public.customer_reviews (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  customer_id uuid NOT NULL,
  order_id uuid NOT NULL,
  product_id uuid,
  overall_rating integer NOT NULL CHECK (overall_rating >= 1 AND overall_rating <= 5),
  food_rating integer CHECK (food_rating >= 1 AND food_rating <= 5),
  service_rating integer CHECK (service_rating >= 1 AND service_rating <= 5),
  ambiance_rating integer CHECK (ambiance_rating >= 1 AND ambiance_rating <= 5),
  review_text text,
  photos jsonb,
  is_anonymous boolean DEFAULT false,
  is_approved boolean DEFAULT false,
  response_text text,
  response_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT customer_reviews_pkey PRIMARY KEY (id),
  CONSTRAINT customer_reviews_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.customer_orders(id),
  CONSTRAINT customer_reviews_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT customer_reviews_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customer_users(id)
);
CREATE TABLE public.customer_users (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  phone character varying NOT NULL UNIQUE,
  email character varying UNIQUE,
  name character varying,
  password_hash character varying NOT NULL,
  birth_date date,
  gender character varying,
  preferences jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  is_active boolean DEFAULT true,
  last_login timestamp with time zone,
  avatar_url text,
  terms_accepted boolean DEFAULT false,
  marketing_consent boolean DEFAULT false,
  CONSTRAINT customer_users_pkey PRIMARY KEY (id)
);
CREATE TABLE public.error_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  restaurant_id uuid,
  error_type character varying NOT NULL,
  error_message text NOT NULL,
  stack_trace text,
  context jsonb,
  request_data jsonb,
  severity character varying DEFAULT 'medium'::character varying CHECK (severity::text = ANY (ARRAY['low'::character varying, 'medium'::character varying, 'high'::character varying, 'critical'::character varying]::text[])),
  status character varying DEFAULT 'open'::character varying CHECK (status::text = ANY (ARRAY['open'::character varying, 'investigating'::character varying, 'resolved'::character varying, 'ignored'::character varying]::text[])),
  resolution_notes text,
  reported_by character varying,
  assigned_to character varying,
  resolved_by character varying,
  resolved_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT error_logs_pkey PRIMARY KEY (id),
  CONSTRAINT error_logs_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id)
);
CREATE TABLE public.favorites (
  user_id uuid NOT NULL,
  menu_item_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT favorites_pkey PRIMARY KEY (user_id, menu_item_id),
  CONSTRAINT favorites_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT favorites_menu_item_id_fkey FOREIGN KEY (menu_item_id) REFERENCES public.menu_items(id)
);
CREATE TABLE public.loyalty_points (
  user_id uuid NOT NULL,
  balance integer NOT NULL DEFAULT 0,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT loyalty_points_pkey PRIMARY KEY (user_id),
  CONSTRAINT loyalty_points_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.loyalty_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  delta integer NOT NULL,
  reason text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT loyalty_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT loyalty_transactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.marquees (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  message text NOT NULL,
  href text,
  priority integer DEFAULT 0,
  is_active boolean DEFAULT true,
  starts_at timestamp with time zone,
  ends_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT marquees_pkey PRIMARY KEY (id)
);
CREATE TABLE public.menu_categories (
  id integer NOT NULL DEFAULT nextval('menu_categories_id_seq'::regclass),
  name text NOT NULL,
  display_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  CONSTRAINT menu_categories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.menu_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  category_id integer,
  name text NOT NULL,
  description text,
  price numeric NOT NULL,
  image_url text,
  is_active boolean DEFAULT true,
  popularity_score integer DEFAULT 0,
  tags ARRAY,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT menu_items_pkey PRIMARY KEY (id),
  CONSTRAINT menu_items_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.menu_categories(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  type text,
  title text,
  body text,
  read_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.order_combo_selections (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  order_item_id uuid NOT NULL,
  rule_id uuid NOT NULL,
  selected_product_id uuid NOT NULL,
  quantity integer DEFAULT 1,
  additional_price numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT order_combo_selections_pkey PRIMARY KEY (id),
  CONSTRAINT order_combo_selections_order_item_id_fkey FOREIGN KEY (order_item_id) REFERENCES public.order_items(id),
  CONSTRAINT order_combo_selections_rule_id_fkey FOREIGN KEY (rule_id) REFERENCES public.combo_selection_rules(id),
  CONSTRAINT order_combo_selections_selected_product_id_fkey FOREIGN KEY (selected_product_id) REFERENCES public.products(id)
);
CREATE TABLE public.order_items (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  order_id uuid NOT NULL,
  product_id uuid,
  combo_id uuid,
  item_type character varying DEFAULT 'product'::character varying,
  product_name character varying NOT NULL,
  product_sku character varying,
  variant_name character varying,
  quantity integer NOT NULL DEFAULT 1,
  unit_price numeric NOT NULL,
  total_price numeric NOT NULL,
  cost_price numeric DEFAULT 0,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'confirmed'::character varying, 'preparing'::character varying, 'ready'::character varying, 'served'::character varying, 'cancelled'::character varying]::text[])),
  ordered_at timestamp with time zone DEFAULT now(),
  preparation_started_at timestamp with time zone,
  ready_at timestamp with time zone,
  served_at timestamp with time zone,
  estimated_prep_time integer,
  actual_prep_time integer,
  special_instructions text,
  modifiers jsonb,
  kitchen_station character varying,
  priority_level integer DEFAULT 3,
  quality_checked boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT order_items_pkey PRIMARY KEY (id),
  CONSTRAINT order_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT order_items_combo_id_fkey FOREIGN KEY (combo_id) REFERENCES public.combo_products(id)
);
CREATE TABLE public.orders (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  restaurant_id uuid NOT NULL,
  table_id uuid,
  session_id uuid,
  order_number character varying NOT NULL UNIQUE,
  order_type character varying DEFAULT 'dine_in'::character varying,
  customer_name character varying,
  customer_phone character varying,
  customer_email character varying,
  table_number integer,
  party_size integer DEFAULT 1,
  subtotal numeric DEFAULT 0,
  discount_amount numeric DEFAULT 0,
  tax_amount numeric DEFAULT 0,
  service_charge numeric DEFAULT 0,
  total_amount numeric DEFAULT 0,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'confirmed'::character varying, 'preparing'::character varying, 'ready'::character varying, 'served'::character varying, 'completed'::character varying, 'cancelled'::character varying]::text[])),
  payment_status character varying DEFAULT 'unpaid'::character varying CHECK (payment_status::text = ANY (ARRAY['unpaid'::character varying, 'partial'::character varying, 'paid'::character varying, 'refunded'::character varying, 'voided'::character varying]::text[])),
  ordered_at timestamp with time zone DEFAULT now(),
  confirmed_at timestamp with time zone,
  preparation_started_at timestamp with time zone,
  ready_at timestamp with time zone,
  served_at timestamp with time zone,
  completed_at timestamp with time zone,
  estimated_ready_time timestamp with time zone,
  estimated_prep_time integer,
  actual_prep_time integer,
  ai_optimized boolean DEFAULT false,
  ai_estimated_prep_time integer,
  ai_recommendations jsonb,
  ai_efficiency_score numeric,
  notes text,
  special_instructions text,
  source character varying DEFAULT 'pos'::character varying,
  created_by character varying,
  updated_by character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  metadata jsonb,
  CONSTRAINT orders_pkey PRIMARY KEY (id),
  CONSTRAINT orders_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id),
  CONSTRAINT orders_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.table_sessions(id),
  CONSTRAINT orders_table_id_fkey FOREIGN KEY (table_id) REFERENCES public.tables(id)
);
CREATE TABLE public.payments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  order_id uuid NOT NULL,
  payment_method character varying NOT NULL CHECK (payment_method::text = ANY (ARRAY['cash'::character varying, 'card'::character varying, 'mobile_pay'::character varying, 'voucher'::character varying, 'points'::character varying, 'bank_transfer'::character varying, 'digital_wallet'::character varying]::text[])),
  payment_provider character varying,
  amount numeric NOT NULL,
  received_amount numeric,
  change_amount numeric,
  tip_amount numeric DEFAULT 0,
  transaction_id character varying,
  reference_number character varying,
  authorization_code character varying,
  card_last_four character varying,
  card_type character varying,
  card_brand character varying,
  mobile_provider character varying,
  mobile_account character varying,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'processing'::character varying, 'completed'::character varying, 'failed'::character varying, 'refunded'::character varying, 'voided'::character varying]::text[])),
  processed_at timestamp with time zone DEFAULT now(),
  confirmed_at timestamp with time zone,
  refund_amount numeric DEFAULT 0,
  refund_reason text,
  refunded_at timestamp with time zone,
  processed_by character varying,
  terminal_id character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  metadata jsonb,
  CONSTRAINT payments_pkey PRIMARY KEY (id),
  CONSTRAINT payments_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id)
);
CREATE TABLE public.pet_interactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  pet_id uuid NOT NULL,
  interaction_type text NOT NULL,
  experience_gained integer NOT NULL DEFAULT 0,
  result text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT pet_interactions_pkey PRIMARY KEY (id),
  CONSTRAINT pet_interactions_pet_id_fkey FOREIGN KEY (pet_id) REFERENCES public.virtual_pets(id)
);
CREATE TABLE public.product_modifiers (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  product_id uuid NOT NULL,
  name character varying NOT NULL,
  description text,
  type character varying NOT NULL,
  price numeric DEFAULT 0,
  is_required boolean DEFAULT false,
  max_selections integer DEFAULT 1,
  sort_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT product_modifiers_pkey PRIMARY KEY (id),
  CONSTRAINT product_modifiers_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.product_variants (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  product_id uuid NOT NULL,
  name character varying NOT NULL,
  sku character varying,
  price_adjustment numeric DEFAULT 0,
  cost_adjustment numeric DEFAULT 0,
  is_default boolean DEFAULT false,
  sort_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT product_variants_pkey PRIMARY KEY (id),
  CONSTRAINT product_variants_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.products (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  restaurant_id uuid NOT NULL,
  category_id uuid,
  name character varying NOT NULL,
  description text,
  sku character varying UNIQUE,
  barcode character varying,
  price numeric NOT NULL DEFAULT 0,
  cost numeric DEFAULT 0,
  image_url text,
  images jsonb,
  sort_order integer DEFAULT 0,
  is_available boolean DEFAULT true,
  is_active boolean DEFAULT true,
  track_inventory boolean DEFAULT false,
  current_stock numeric DEFAULT 0,
  min_stock numeric DEFAULT 0,
  max_stock numeric DEFAULT 0,
  unit character varying DEFAULT 'item'::character varying,
  prep_time_minutes integer DEFAULT 15,
  cook_time_minutes integer DEFAULT 0,
  total_time_minutes integer DEFAULT 15,
  calories integer,
  nutrition_info jsonb,
  allergens jsonb,
  dietary_tags jsonb,
  ai_popularity_score numeric DEFAULT 0.5,
  ai_recommended boolean DEFAULT false,
  ai_demand_forecast jsonb,
  total_sold integer DEFAULT 0,
  revenue_generated numeric DEFAULT 0,
  last_sold_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  metadata jsonb,
  custom_fields jsonb,
  CONSTRAINT products_pkey PRIMARY KEY (id),
  CONSTRAINT products_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(id),
  CONSTRAINT products_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  full_name text,
  phone text,
  birthday date,
  avatar_url text,
  member_tier text DEFAULT 'bronze'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.purchase_order_items (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  purchase_order_id uuid NOT NULL,
  raw_material_id uuid NOT NULL,
  quantity_ordered numeric NOT NULL,
  quantity_received numeric DEFAULT 0,
  unit character varying NOT NULL,
  unit_cost numeric NOT NULL,
  total_cost numeric NOT NULL,
  quality_checked boolean DEFAULT false,
  quality_rating integer CHECK (quality_rating >= 1 AND quality_rating <= 5),
  quality_notes text,
  expiry_date date,
  lot_number character varying,
  batch_number character varying,
  status character varying DEFAULT 'ordered'::character varying CHECK (status::text = ANY (ARRAY['ordered'::character varying, 'received'::character varying, 'rejected'::character varying, 'cancelled'::character varying]::text[])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT purchase_order_items_pkey PRIMARY KEY (id),
  CONSTRAINT purchase_order_items_raw_material_id_fkey FOREIGN KEY (raw_material_id) REFERENCES public.raw_materials(id),
  CONSTRAINT purchase_order_items_purchase_order_id_fkey FOREIGN KEY (purchase_order_id) REFERENCES public.purchase_orders(id)
);
CREATE TABLE public.purchase_orders (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  restaurant_id uuid NOT NULL,
  supplier_id uuid NOT NULL,
  purchase_number character varying NOT NULL UNIQUE,
  order_date date NOT NULL,
  expected_delivery_date date,
  actual_delivery_date date,
  subtotal numeric NOT NULL DEFAULT 0,
  tax_amount numeric DEFAULT 0,
  discount_amount numeric DEFAULT 0,
  shipping_cost numeric DEFAULT 0,
  total_amount numeric NOT NULL DEFAULT 0,
  status character varying DEFAULT 'draft'::character varying CHECK (status::text = ANY (ARRAY['draft'::character varying, 'sent'::character varying, 'confirmed'::character varying, 'partially_received'::character varying, 'received'::character varying, 'completed'::character varying, 'cancelled'::character varying]::text[])),
  payment_status character varying DEFAULT 'pending'::character varying CHECK (payment_status::text = ANY (ARRAY['pending'::character varying, 'partial'::character varying, 'paid'::character varying, 'overdue'::character varying]::text[])),
  invoice_number character varying,
  invoice_date date,
  payment_due_date date,
  notes text,
  internal_notes text,
  created_by character varying,
  approved_by character varying,
  received_by character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT purchase_orders_pkey PRIMARY KEY (id),
  CONSTRAINT purchase_orders_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id),
  CONSTRAINT purchase_orders_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id)
);
CREATE TABLE public.raw_materials (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  restaurant_id uuid NOT NULL,
  supplier_id uuid,
  name character varying NOT NULL,
  category character varying NOT NULL,
  sku character varying UNIQUE,
  barcode character varying,
  unit character varying NOT NULL,
  current_stock numeric NOT NULL DEFAULT 0,
  min_stock numeric NOT NULL DEFAULT 0,
  max_stock numeric NOT NULL DEFAULT 0,
  reorder_point numeric NOT NULL DEFAULT 0,
  cost_per_unit numeric NOT NULL DEFAULT 0,
  last_purchase_cost numeric,
  average_cost numeric,
  shelf_life_days integer,
  storage_location character varying,
  storage_conditions text,
  quality_standards text,
  inspection_required boolean DEFAULT false,
  last_restock_date timestamp with time zone,
  last_used_date timestamp with time zone,
  total_consumed numeric DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT raw_materials_pkey PRIMARY KEY (id),
  CONSTRAINT raw_materials_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id),
  CONSTRAINT raw_materials_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id)
);
CREATE TABLE public.receipts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  order_id uuid NOT NULL,
  payment_id uuid,
  receipt_number character varying NOT NULL UNIQUE,
  invoice_type character varying DEFAULT 'receipt'::character varying,
  buyer_name character varying,
  buyer_tax_id character varying,
  buyer_address text,
  buyer_email character varying,
  items jsonb NOT NULL,
  subtotal numeric NOT NULL,
  discount_amount numeric DEFAULT 0,
  tax_amount numeric NOT NULL,
  service_charge numeric DEFAULT 0,
  total_amount numeric NOT NULL,
  payment_method character varying NOT NULL,
  received_amount numeric,
  change_amount numeric,
  status character varying DEFAULT 'issued'::character varying,
  issued_at timestamp with time zone DEFAULT now(),
  printed_at timestamp with time zone,
  emailed_at timestamp with time zone,
  voided_at timestamp with time zone,
  issued_by character varying,
  void_reason text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT receipts_pkey PRIMARY KEY (id),
  CONSTRAINT receipts_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT receipts_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES public.payments(id)
);
CREATE TABLE public.reservations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  restaurant_id uuid NOT NULL,
  table_id uuid,
  customer_name character varying NOT NULL,
  customer_phone character varying NOT NULL,
  customer_email character varying,
  party_size integer NOT NULL CHECK (party_size > 0 AND party_size <= 20),
  reservation_date date NOT NULL,
  reservation_time time without time zone NOT NULL,
  status character varying NOT NULL DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'confirmed'::character varying, 'seated'::character varying, 'completed'::character varying, 'cancelled'::character varying, 'no_show'::character varying]::text[])),
  special_requests text,
  notes text,
  created_via character varying DEFAULT 'ai_chat'::character varying CHECK (created_via::text = ANY (ARRAY['ai_chat'::character varying, 'manual'::character varying, 'phone'::character varying, 'website'::character varying]::text[])),
  confidence_score numeric DEFAULT 1.0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  confirmed_at timestamp with time zone,
  seated_at timestamp with time zone,
  completed_at timestamp with time zone,
  cancelled_at timestamp with time zone,
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT reservations_pkey PRIMARY KEY (id),
  CONSTRAINT reservations_table_id_fkey FOREIGN KEY (table_id) REFERENCES public.tables(id),
  CONSTRAINT reservations_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id)
);
CREATE TABLE public.restaurant_closures (
  id bigint NOT NULL DEFAULT nextval('restaurant_closures_id_seq'::regclass),
  date date NOT NULL UNIQUE,
  reason text,
  CONSTRAINT restaurant_closures_pkey PRIMARY KEY (id)
);
CREATE TABLE public.restaurant_holidays (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  restaurant_id uuid NOT NULL,
  holiday_date date NOT NULL,
  holiday_name character varying NOT NULL,
  is_recurring boolean DEFAULT false,
  recurrence_type character varying DEFAULT NULL::character varying CHECK (recurrence_type::text = ANY (ARRAY['yearly'::character varying, 'monthly'::character varying, 'weekly'::character varying]::text[])),
  is_closed boolean DEFAULT true,
  special_hours jsonb,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT restaurant_holidays_pkey PRIMARY KEY (id),
  CONSTRAINT restaurant_holidays_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id)
);
CREATE TABLE public.restaurant_settings (
  id integer NOT NULL DEFAULT 1,
  open_time text NOT NULL DEFAULT '17:00'::text,
  close_time text NOT NULL DEFAULT '21:00'::text,
  slot_interval_min integer NOT NULL DEFAULT 30,
  dining_duration_min integer NOT NULL DEFAULT 90,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT restaurant_settings_pkey PRIMARY KEY (id)
);
CREATE TABLE public.restaurants (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name character varying NOT NULL,
  address text,
  phone character varying,
  email character varying,
  website character varying,
  tax_rate numeric DEFAULT 0.1000,
  service_charge_rate numeric DEFAULT 0.0000,
  currency character varying DEFAULT 'TWD'::character varying,
  timezone character varying DEFAULT 'Asia/Taipei'::character varying,
  business_hours jsonb,
  settings jsonb,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  metadata jsonb,
  custom_fields jsonb,
  reservation_settings jsonb DEFAULT '{"businessHours": {"friday": {"isOpen": true, "openTime": "14:00", "closeTime": "21:00"}, "monday": {"isOpen": true, "openTime": "14:00", "closeTime": "21:00"}, "sunday": {"isOpen": true, "openTime": "14:00", "closeTime": "21:00"}, "tuesday": {"isOpen": true, "openTime": "14:00", "closeTime": "21:00"}, "saturday": {"isOpen": true, "openTime": "14:00", "closeTime": "21:00"}, "thursday": {"isOpen": true, "openTime": "14:00", "closeTime": "21:00"}, "wednesday": {"isOpen": true, "openTime": "14:00", "closeTime": "21:00"}}, "autoAssignment": {"enabled": true, "capacityWeight": 0.5, "aiPriorityWeight": 0.2, "preferenceWeight": 0.3}, "reservationSettings": {"lastReservationTime": "19:30", "mealDurationMinutes": 90, "slotDurationMinutes": 30, "maxAdvanceBookingDays": 30, "minAdvanceBookingHours": 2}}'::jsonb,
  CONSTRAINT restaurants_pkey PRIMARY KEY (id)
);
CREATE TABLE public.reviews (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  menu_item_id uuid,
  rating smallint NOT NULL CHECK (rating >= 1 AND rating <= 5),
  comment text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT reviews_pkey PRIMARY KEY (id),
  CONSTRAINT reviews_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT reviews_menu_item_id_fkey FOREIGN KEY (menu_item_id) REFERENCES public.menu_items(id)
);
CREATE TABLE public.stock_movements (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  restaurant_id uuid NOT NULL,
  item_id uuid NOT NULL,
  item_type character varying NOT NULL,
  movement_type character varying NOT NULL,
  quantity numeric NOT NULL,
  unit character varying NOT NULL,
  unit_cost numeric,
  total_cost numeric,
  reference_type character varying,
  reference_id uuid,
  reference_number character varying,
  reason character varying,
  notes text,
  created_by character varying,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT stock_movements_pkey PRIMARY KEY (id),
  CONSTRAINT stock_movements_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id)
);
CREATE TABLE public.suppliers (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  restaurant_id uuid NOT NULL,
  name character varying NOT NULL,
  code character varying,
  contact_person character varying,
  phone character varying,
  email character varying,
  website character varying,
  address text,
  payment_terms character varying,
  delivery_days jsonb,
  min_order_amount numeric DEFAULT 0,
  credit_limit numeric,
  discount_rate numeric DEFAULT 0,
  quality_rating integer CHECK (quality_rating >= 1 AND quality_rating <= 5),
  delivery_rating integer CHECK (delivery_rating >= 1 AND delivery_rating <= 5),
  service_rating integer CHECK (service_rating >= 1 AND service_rating <= 5),
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT suppliers_pkey PRIMARY KEY (id),
  CONSTRAINT suppliers_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id)
);
CREATE TABLE public.table_reservations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  restaurant_id uuid NOT NULL,
  table_id uuid,
  customer_name character varying NOT NULL,
  customer_phone character varying,
  customer_email character varying,
  customer_notes text,
  party_size integer NOT NULL,
  reservation_time timestamp with time zone NOT NULL,
  duration_minutes integer DEFAULT 120,
  estimated_end_time timestamp with time zone,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'confirmed'::character varying, 'seated'::character varying, 'completed'::character varying, 'cancelled'::character varying, 'no_show'::character varying]::text[])),
  special_requests text,
  occasion character varying,
  deposit_amount numeric DEFAULT 0,
  deposit_paid boolean DEFAULT false,
  deposit_payment_method character varying,
  notes text,
  created_by character varying,
  confirmed_at timestamp with time zone,
  seated_at timestamp with time zone,
  completed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  reservation_type character varying DEFAULT 'dining'::character varying,
  adult_count integer DEFAULT 0,
  child_count integer DEFAULT 0,
  child_chair_needed boolean DEFAULT false,
  CONSTRAINT table_reservations_pkey PRIMARY KEY (id),
  CONSTRAINT table_reservations_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id),
  CONSTRAINT table_reservations_table_id_fkey FOREIGN KEY (table_id) REFERENCES public.tables(id)
);
CREATE TABLE public.table_sessions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  restaurant_id uuid NOT NULL,
  table_id uuid NOT NULL,
  reservation_id uuid,
  customer_name character varying,
  party_size integer NOT NULL,
  seated_at timestamp with time zone NOT NULL DEFAULT now(),
  estimated_duration integer DEFAULT 120,
  actual_duration integer,
  status character varying DEFAULT 'occupied'::character varying CHECK (status::text = ANY (ARRAY['occupied'::character varying, 'ordering'::character varying, 'dining'::character varying, 'paying'::character varying, 'completed'::character varying]::text[])),
  total_amount numeric DEFAULT 0,
  total_orders integer DEFAULT 0,
  service_rating integer CHECK (service_rating >= 1 AND service_rating <= 5),
  service_feedback text,
  notes text,
  completed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT table_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT table_sessions_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id),
  CONSTRAINT table_sessions_reservation_id_fkey FOREIGN KEY (reservation_id) REFERENCES public.table_reservations(id),
  CONSTRAINT table_sessions_table_id_fkey FOREIGN KEY (table_id) REFERENCES public.tables(id)
);
CREATE TABLE public.tables (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  restaurant_id uuid NOT NULL,
  table_number integer NOT NULL,
  name character varying,
  capacity integer DEFAULT 4,
  min_capacity integer DEFAULT 1,
  max_capacity integer,
  status character varying DEFAULT 'available'::character varying CHECK (status::text = ANY (ARRAY['available'::character varying, 'occupied'::character varying, 'reserved'::character varying, 'cleaning'::character varying, 'maintenance'::character varying, 'inactive'::character varying]::text[])),
  floor_level integer DEFAULT 1,
  zone character varying,
  position_x numeric DEFAULT 0,
  position_y numeric DEFAULT 0,
  table_type character varying DEFAULT 'square'::character varying,
  features jsonb,
  qr_code text,
  qr_enabled boolean DEFAULT true,
  ai_assignment_priority integer DEFAULT 5,
  ai_features_score jsonb,
  current_session_id uuid,
  last_occupied_at timestamp with time zone,
  last_cleaned_at timestamp with time zone,
  cleaning_duration_minutes integer DEFAULT 15,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  metadata jsonb,
  CONSTRAINT tables_pkey PRIMARY KEY (id),
  CONSTRAINT tables_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id)
);
CREATE TABLE public.takeaway_sequences (
  date date NOT NULL,
  last_sequence integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT takeaway_sequences_pkey PRIMARY KEY (date)
);
CREATE TABLE public.user_achievements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  achievement_id uuid NOT NULL,
  ai_pet_id uuid NOT NULL,
  achieved_at timestamp with time zone DEFAULT now(),
  progress_data jsonb DEFAULT '{}'::jsonb,
  reward_claimed boolean DEFAULT false,
  claimed_at timestamp with time zone,
  CONSTRAINT user_achievements_pkey PRIMARY KEY (id),
  CONSTRAINT user_achievements_achievement_id_fkey FOREIGN KEY (achievement_id) REFERENCES public.achievements(id),
  CONSTRAINT user_achievements_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT user_achievements_ai_pet_id_fkey FOREIGN KEY (ai_pet_id) REFERENCES public.ai_pets(id)
);
CREATE TABLE public.user_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  session_token character varying NOT NULL UNIQUE,
  ip_address inet,
  user_agent text,
  device_info jsonb,
  created_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone NOT NULL,
  last_used_at timestamp with time zone DEFAULT now(),
  is_active boolean DEFAULT true,
  CONSTRAINT user_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT user_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  phone character varying NOT NULL UNIQUE,
  email character varying UNIQUE,
  name character varying,
  avatar_url text,
  birthday date,
  preferred_language character varying DEFAULT 'zh-TW'::character varying,
  timezone character varying DEFAULT 'Asia/Taipei'::character varying,
  registration_source character varying DEFAULT 'mobile'::character varying,
  is_active boolean DEFAULT true,
  last_active_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  notification_preferences jsonb DEFAULT '{}'::jsonb,
  privacy_settings jsonb DEFAULT '{}'::jsonb,
  custom_preferences jsonb DEFAULT '{}'::jsonb,
  login_count integer DEFAULT 0,
  CONSTRAINT users_pkey PRIMARY KEY (id)
);
CREATE TABLE public.virtual_pets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id text NOT NULL DEFAULT 'default'::text,
  name text NOT NULL,
  species text NOT NULL,
  level integer NOT NULL DEFAULT 1,
  experience integer NOT NULL DEFAULT 0,
  experience_to_next integer NOT NULL DEFAULT 100,
  health integer NOT NULL DEFAULT 100,
  max_health integer NOT NULL DEFAULT 100,
  happiness integer NOT NULL DEFAULT 80,
  max_happiness integer NOT NULL DEFAULT 100,
  energy integer NOT NULL DEFAULT 90,
  max_energy integer NOT NULL DEFAULT 100,
  hunger integer NOT NULL DEFAULT 30,
  max_hunger integer NOT NULL DEFAULT 100,
  chat_skill integer NOT NULL DEFAULT 5,
  service_skill integer NOT NULL DEFAULT 5,
  loyalty_skill integer NOT NULL DEFAULT 5,
  mood text NOT NULL DEFAULT 'happy'::text,
  activity text NOT NULL DEFAULT 'chatting'::text,
  last_feed_time timestamp with time zone NOT NULL DEFAULT (now() - '02:00:00'::interval),
  last_interaction_time timestamp with time zone NOT NULL DEFAULT (now() - '00:30:00'::interval),
  appearance jsonb NOT NULL DEFAULT jsonb_build_object('color', 'orange', 'pattern', 'standard', 'accessories', '[]', 'emoji', '🦊'),
  total_interactions integer NOT NULL DEFAULT 0,
  total_feedings integer NOT NULL DEFAULT 0,
  days_alive integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT virtual_pets_pkey PRIMARY KEY (id)
);
CREATE TABLE public.waitlist (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  party_size integer NOT NULL,
  status text NOT NULL DEFAULT 'waiting'::text,
  position integer,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT waitlist_pkey PRIMARY KEY (id),
  CONSTRAINT waitlist_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);